development:
  WEBSITE_URL: https://23b8-2401-4900-1c67-7578-47cd-3990-cf81-9130.ngrok-free.app
  STRIPE_API_KEY: sk_test_rTxyFQAuEqMjT0DJ0XPGzFYU
  PRODUCT_ID: price_1MkK9WEKG9XSLvIWjQ9dqONf
  RAZOR_PAY_KEY_ID: rzp_test_gRev74AlPRTaDK
  RAZOR_PAY_KEY_SECRET: L9HX1xg9fvbR54WMO9Jcj1zZ